### ISSUE TITLE
Enhance console command output

### ISSUE THREAD

**Issue by fwolfsjaeger** [AvaiBookSports/DoctrineMigrationsMultipleDatabaseBundle#26]
When running any command without restricting it to an EntityManager, it is currently not so easy to tell what output belongs to what EntityManager.

I would like to print the EntityManager name before calling the actual command for a single EntityManager.

**Comment by devnix** [comment]
It should run the one you configured as the default one, the same way as if you were not using this bundle. Not sure if I'm going to merge this kind of changes (I'm considering archiving the project)

**Comment by fwolfsjaeger** [comment]
It runs the given command for all configured entity managers right now.

Archiving this project would be a shame, it's a great improvement for DoctrineMigrations, which still doesn't provide an alternative solution.

**Comment by devnix** [comment]
>Archiving this project would be a shame, it's a great improvement for DoctrineMigrations, which still doesn't provide an alternative solution.

I miss a lot this kind of functionality, but the old saying "don't fight your framework" is kinda biting my ass all the time.

To be honest, if I had this problem again I would use a Makefile, I was so reluctant to start using a Makefile just for this purpose that I started to bodge this whole thing. 

In the end, it's still a bodge that I have to maintain and keep up with future Symfony/Doctrine versions, waiting to break at any moment, and yes it's still a shame that the upstream project does not have this feature. And to be honest, again, I would not opt for Doctrine for a new project, at least I would not use the ORM at all.

> It runs the given command for all configured entity managers right now.

This would be kind of a breaking change that I would prefer not to do in the current state: This package seems to have a [certain amount of installations](https://packagist.org/packages/avaibooksports/doctrine-migrations-multiple-database-bundle/stats#dev-main) according to packagist.org that might break a lot of CI/CD.

I would merge a pull request like this one for a new major version, but I'm probably not doing that.
