### ISSUE TITLE
Allow installation under php 8

### ISSUE THREAD

**Issue by mdeherder** [AvaiBookSports/DoctrineMigrationsMultipleDatabaseBundle#3]
See title.

**Comment by devnix** [comment]
@mdeherder let me know if you can install the dev version, then I'll release the tag!

**Comment by mdeherder** [comment]
Install **OK** from `dev-main e94217b`

**Comment by devnix** [comment]
Ok, should work on 0.3.1 tag. Thank you for reporting!
