### ISSUE TITLE
Allowing "connection" parameter

### ISSUE THREAD

**Issue by dkrizan** [AvaiBookSports/DoctrineMigrationsMultipleDatabaseBundle#4]
**Current behavior**
Parameter `connection` is not allowed as CLI argument as well in configuration.

**Summary**
I am aware of the reason why the `connection` (and `em` also) parameter is no longer needed in configuration, but we would like to set different `connection` for a migrations than the one set in doctrine configuration as we want to use a another DB user to execute the migrations.

**Expected behavior**
Allow to override default `connection` by setting in config file or passing it as argument into command.

**Comment by devnix** [comment]
Maybe I'm misunderstanding your feature request, but I think it's out of the scope of this package.
