### ISSUE TITLE
Undefined class constant 'SUCCESS' (not compatible with symfony/console 4.4)

### ISSUE THREAD

**Issue by mattyhansen** [AvaiBookSports/DoctrineMigrationsMultipleDatabaseBundle#5]
## Error

When running the commands, `return self::SUCCESS;` is used 
But that is only available after symfony/console 5.1
  - https://github.com/symfony/console/commit/27327a59875896d8b8e577ccddc35d92d7654664

For example, if symfony/console 4.4 is used then we will see this error:

![image](https://user-images.githubusercontent.com/4113603/132260690-9d695898-8b06-4a7d-8404-f4696cfc9b7e.png)

## Example

https://github.com/AvaiBookSports/DoctrineMigrationsMultipleDatabaseBundle/blob/main/src/Command/Doctrine/StatusCommand.php

![image](https://user-images.githubusercontent.com/4113603/132260655-d1100449-5ed4-4202-831a-c75397e2c486.png)

## Solution request

- `return 0` instead of `return self:SUCCESS`
OR 
- update `src/Command/Doctrine/AbstractCommand.php` to include:
```
public const SUCCESS = 0;
public const FAILURE = 1;
```

**Comment by devnix** [comment]
@mattyhansen please confirm if `main` version works for you so I can tag a new stable version

**Comment by mattyhansen** [comment]
@devnix - yes, no problems with `main` branch now. Thanks for quick fix!
