### ISSUE TITLE
Symfony V6

### ISSUE THREAD

**Issue by mdeherder** [AvaiBookSports/DoctrineMigrationsMultipleDatabaseBundle#7]
Please allow symfony V6.

**Comment by devnix** [comment]
Please, feel free to clone the repo and test first if this bundle still works with Symfony 6 and if it does, to open a pull request. I'll be happy to merge and tag it 😄

**Comment by mdeherder** [comment]
I'm sorry but I don't have the necessary knowledge to do this job.

**Comment by mhpcc** [comment]
pr #8 tackles this. as far as I see all methods already had type parameters set

**Comment by rafa-as** [comment]
Hi there! We also need compatibility with Symfony 6. Can you check the #8

**Comment by devnix** [comment]
@rafa-as  @mhpcc  @mdeherder Please confirm it works against `dev-master`, and I will push a new tag
